mysql:
    rootPassword: ENC[AES256_GCM,data:87PjQAi6,iv:DD3CqizVtAOW0YBPEy7QU9w/c41/CiT5DrEIIINGRnY=,tag:r5HnOXAWRk69FLk5i4FBKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-12-04T08:56:36Z'
    mac: ENC[AES256_GCM,data:arx2auzbGkVX7eyh05Jmx4hF77L253aLgEOkUT+dtx7V1Y5FMKGv8yNIzpSg2vcVekmPuXMHUHlBKMJpc6M+aVnGcPqwcBeN0YwmLkBtfCCit7a8WYCpxvr0aVxJulWZ0eYjZjlnnXzBvPXQr0lmeiW9d65bDFB5qdDmdR+VEow=,iv:izEYHBiWdQK/6YithOVNvwC0rEyMfj7bIfu8Ss1pWkc=,tag:2/1gGsl2Rxya+v15c0sJpg==,type:str]
    pgp:
    -   created_at: '2019-12-04T08:56:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAydKkem05+nbAQv9Fr1qmAyleNzs2rjWn5uTr3kQyWcvJxULM/qXT5EvILkk
            8kyB/UJjaxMqUfO8SrZ+1W3vB2PGrU4nFT5QrxiUCPSVA9YuKiGU4lh5Dp1raovS
            cfGUXANmOZrKiAFYyNHee/zK+vb5+qX+Xsk8xzNgJQkHhqceJliaIx4Wm8XohVwh
            b7hVoGDImdcxrnPMPDIXNE4qUZrkaphBn4laSq5EfGSyaZPqpOEzRhPNpB3o5ozp
            AGEwQNgjrsvPgOzsEYfAgHGH5a3n5/v8ELi59hGIj0lmpRF3jJs1T6akuNj0b8HT
            o+akoRTyNvp/1oDc6OxjnLPXGrj6/UT1meSoyIJkgstDX7arOdyRjsafqqlM0qP4
            +WzM6rbun3nRNxMkY76n11J5HJryzmku9EN/3YwoSUZq3YPtDZiI/tnoEvMeadnm
            BW05fuiclBoNmkU2Fl6V/3QdVg4/6YmJX6c9Vlxo6WvfB/yMyBjGuemBFmj72xQd
            REL8Y86axpUDTM3tdSgT0l4B+neMcNQpfYAjuFhrm8w6wOQ4mSXIu+ZUL2RaFiEp
            NfcnSqwBo8KTQMOxxPBMQktP/xYSKOF4Zl4mR8ERilQ1q5ZPIMmb7A8Za3fIGDlh
            UPj4t6THww3D+7Gyz7q+
            =bvO9
            -----END PGP MESSAGE-----
        fp: AE4089EA47C54F3A0E3616B4C7491A86E4D6DB50
    unencrypted_suffix: _unencrypted
    version: 3.5.0
