# -*- mode: ruby -*-
# vi: set ft=ruby :

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", path: 'setup.sh'

  config.vm.define "master-1" do |master|
    master.vm.hostname = 'master-1'

    master.vm.network "private_network", ip: "192.168.33.100"
    master.vm.network "forwarded_port", guest: 6443, host: 6443

    master.vm.provider "virtualbox" do |vb|
      vb.name = "master-1"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "slave-1" do |slave|
    slave.vm.hostname = 'slave-1'

    slave.vm.network "private_network", ip: "192.168.33.10"

    slave.vm.provider "virtualbox" do |vb|
      vb.name = "slave-1"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
