---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    tier: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs
    endpointsNamespace: default
    path: mysql
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  selector:
    matchLabels:
      tier: mysql
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
