---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    tier: redis
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs
    endpointsNamespace: default
    path: redis
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  selector:
    matchLabels:
      tier: redis
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
