apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistentvolumeclaim
  namespace: staging
spec:
  storageClassName: ""
  volumeName: database-persistentvolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
