apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: staging
spec:
  selector:
    tier: web
    environment: staging
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: staging
      tier: web
  template:
    metadata:
      labels:
        environment: staging
        tier: web
    spec:
      containers:
        - name: web
          image: registry.hub.docker.com/moonlight8978/kube-demo:web
          ports:
            - containerPort: 80
