version: "3.7"
services:
  web:
    build:
      context: web
      dockerfile: ../cluster/development/web.Dockerfile
    command: yarn start
    volumes:
      - ./web:/app
    ports:
      - 4080:3000
    restart: always
    environment:
      NODE_ENV: development

  server:
    build:
      context: server
      dockerfile: ../cluster/development/server.Dockerfile
    command: yarn start
    volumes:
      - ./server:/app
    ports:
      - 4000:3000
    restart: always
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
