# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "slave-1"

  config.vm.network "private_network", ip: "192.168.33.60"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "slave"
    vb.memory = "2048"
    vb.cpus = 2
  end
end
