apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: staging
spec:
  selector:
    tier: server
    environment: staging
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: server
      environment: staging
  template:
    metadata:
      labels:
        environment: staging
        tier: server
    spec:
      containers:
        - name: server
          image: registry.hub.docker.com/moonlight8978/kube-demo:server
          ports:
            - containerPort: 3000
