apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistentvolumeclaim
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
