apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - port: 1

---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.148.0.6
    ports:
      - port: 1
  - addresses:
      - ip: 10.148.0.7
    ports:
      - port: 1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-persistentvolume
spec:
  storageClassName: manual
  capacity:
    storage: 4.95Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: database
    readOnly: false
