apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
subsets:
  - addresses:
      - ip: 172.16.0.210
    ports:
      - port: 1
  - addresses:
      - ip: 172.16.0.220
    ports:
      - port: 1

---
apiVersion: 1
kind: Service
metadata:
  name: glusterfs
spec:
  ports:
    - port: 1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistentvolume
spec:
  storageClassName: database
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-endpoints
    path: database
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistentvolumeclaim
  namespace: staging
spec:
  storageClassName: database
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
