apiVersion: v1
kind: Namespace
metadata:
  name: traefik-ingress

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-serviceaccount
  namespace: traefik-ingress

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: traefik-ingress-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-serviceaccount
    namespace: traefik-ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress
  namespace: traefik-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik-ingress
    spec:
      serviceAccountName: traefik-ingress-serviceaccount
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v2.0.1
          name: traefik-ingress-lb
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8080
          args:
            - --providers.kubernetesingress=true
            - --api.dashboard=true
            - --ping=true
            - --api=true
          livenessProbe:
            exec:
              command:
                - traefik
                - healthcheck
                - --ping
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - traefik
                - healthcheck
                - --ping
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  namespace: traefik-ingress
spec:
  selector:
    app.kubernetes.io/name: traefik-ingress
  ports:
    - name: admin
      port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: traefik-ingress
spec:
  selector:
    app.kubernetes.io/name: traefik-ingress
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
