version: "3.7"
services:
  web:
    image: moonlight8978/kube-demo-web:latest
    build:
      context: web
      dockerfile: ../cluster/staging/web.Dockerfile
      target: appserver
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY

  assets:
    image: moonlight8978/kube-demo-assets:latest
    build:
      context: web
      dockerfile: ../cluster/staging/web.Dockerfile
      target: webserver
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY
