version: "3.7"
services:
  web:
    image: moonlight8978/kube-demo:web
    build:
      context: .
      dockerfile: cluster/staging/web.Dockerfile
    environment:
      NODE_ENV: staging
  server:
    image: moonlight8978/kube-demo:server
    build:
      context: server
      dockerfile: ../cluster/staging/server.Dockerfile
    environment:
      NODE_ENV: staging
