version: "3.7"
services:
  web:
    image: asia.gcr.io/static-mediator-245800/kube-demo-web:latest
    build:
      context: web
      dockerfile: ../cluster/staging/web.Dockerfile
      target: appserver
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY

  assets-caching:
    image: asia.gcr.io/static-mediator-245800/kube-demo-assets-caching:latest
    build:
      context: web
      dockerfile: ../cluster/staging/web.Dockerfile
      target: webserver
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY
